
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from tkinter.messagebox import showinfo
from tkinter.filedialog import askopenfilename  

from PIL import Image, ImageFilter
import subprocess

import os

import shutil


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\lance\Documents\Tkinter-Designer-master\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def process(name:str):
    showinfo("Choose an image", "Make sure to choose an image with png format with dimensions of 192x490 pixels, otherwize it will be cropped.")
    image_path = askopenfilename(filetypes=[("Image", "png, jpg")])

    image = Image.open(image_path)
    
    if image.width < image.height:
        image.thumbnail((10000, 490))
    else: image.thumbnail((192, 1000))
    
    image = image.crop((0, 0, 192, 490))
    
    blurImage = image.filter(ImageFilter.GaussianBlur(5))
    
    path = f"data/watchfaces/{name}/"
    
    image.save(path + "assets/0.png", "PNG")
    blurImage.save(path + "assets/bg1.png", "PNG")
    
    
    subprocess.check_call([r"data/zmake/zmake.exe", path])
    
    shutil.rmtree("/output/")
    
    os.makedirs("/output")
    
    shutil.copytree(path + "dist", "output/") 
    
    shutil.rmtree(path + "dist/")
    shutil.rmtree(path + "build/")
        


window = Tk()

window.title("Band 7 watchface creator")
window.geometry("687x429")
window.configure(bg = "#FFFFFF")

window.iconbitmap("assets/icon.ico")



canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 429,
    width = 687,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    687.0,
    53.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    209.0,
    53.0,
    fill="#3D3D3D",
    outline="")

canvas.create_text(
    10.0,
    15.0,
    anchor="nw",
    text="Band 7 Watchface Creator",
    fill="#FFFFFF",
    font=("Bahnschrift", 16 * -1)
)

canvas.create_rectangle(
    20.0,
    70.0,
    315.0,
    310.0,
    fill="#D9D9D9",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    77.0,
    189.0,
    image=image_image_1
)

button_1 = Button(
    text="INSTALL NOW",
    foreground="#FFFFFF",
    activeforeground="white",
    background="black",
    activebackground="gray",
    font=("Bahnschrift", 12 * -1),
    borderwidth=0,
    highlightthickness=0,
    command=lambda: process("Widget View"),
    relief="flat"
)
button_1.place(
    x=133.0,
    y=246.0,
    width=166.0,
    height=50.0
)



canvas.create_text(
    128.0,
    125.0,
    anchor="nw",
    text="A watchface with a customizable \nbackground and a widget page. \nPractical if you want a simple but\nusable one.",
    fill="#000000",
    font=("Bahnschrift", 12 * -1)
)

canvas.create_text(
    127.0,
    86.0,
    anchor="nw",
    text="Widget view",
    fill="#000000",
    font=("Bahnschrift", 16 * -1)
)
window.resizable(False, False)
window.mainloop()
